apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ofw
  labels:
    app: mysql
type: Opaque
stringData:
  mysql-root-password: "root_password_change_me"
  mysql-user: "ofw_user"
  mysql-password: "ofw_password_change_me"
  mysql-database: "ofw_db"
